### ISSUE TITLE
Release Plan for Next Release

### ISSUE THREAD

**Issue by imdeepmind** [imdeepmind/NeuralPy#100]
Release Plan for Next Release

 - [x] Layers 
    - [x] Work on Linear layers to make sure that it works in all cases
    - [x] Work on Convolution layers to make sure that it works in all cases 
    - [x] Work on Pooling layers to make sure that it works in all cases
    - [x] Work on Normalization layers to make sure that it works in all cases
    - [x] Work on Regularization layers to make sure that it works in all cases
  - [x] Activation Functions
    - [x] Test all activation functions
  - [x] Restructuring all the layers into modules
  - [x] Test script improvement
  - [x] Documentation fixes
  - [x] Update the documentation website
  - [x] Work on library stability
  - [x] Add a lot of examples
  - [ ] Add more blogs and code examples for newbies 
  - [x] Code cleanup and improvement

**In the next release we'll not work on Recurrent Layers**

**Comment by jeffin07** [comment]
@imdeepmind Can you explain what are the examples you are expecting in this release?If you can name some maybe it will be helpful

**Comment by imdeepmind** [comment]
@jeffin07 If you want, you can add any examples using ANN and CNN
