### ISSUE TITLE
BatchNorm1D layer is not working, completely broken.

### ISSUE THREAD

**Issue by imdeepmind** [imdeepmind/NeuralPy#126]
**Describe the bug**
BatchNorm1D layer is completely broken. Can not be used in any way.

**To Reproduce**

Run the following model:
```
model.add(Conv1D(filters=32, input_shape=(1,28,28), kernel_size=3))
model.add(BatchNorm1D(10))
model.add(ReLU())
```

**Platform information**
 - OS: Windows
 - Python: 3.7
 - Version: Unrelease version of NeuralPy (latest code from `master` branch)

**Comment by jeffin07** [comment]
@imdeepmind are you working on this issue?

**Comment by imdeepmind** [comment]
Have not started working on it
