### ISSUE TITLE
MISC Doc Issues

### ISSUE THREAD

**Issue by imdeepmind** [imdeepmind/NeuralPy#131]
MISC Issues with Docs:	
        - Name of the BatchNorm3D layer is invalid
	- There is no space between layer name and the word layer in Dropout3D layer
	- Sentence issue in the Introduction for the Model class
	- The title for Conv3D layer is wrong, it should be Conv3D

**Comment by jeffin07** [comment]
@imdeepmind Can you please elaborate?. I didn't find some issues you mentioned here like Cov3D title is Conv3D.

**Comment by imdeepmind** [comment]
I'm working on it, leave it, there are some issues with the documentation
