### ISSUE TITLE
An issue with numpy array to PyTorch tensor conversation

### ISSUE THREAD

**Issue by imdeepmind** [imdeepmind/NeuralPy#74]
**Describe the bug**
An issue with numpy array to PyTorch tensor conversation

The data type is getting messed up when we try to convert a numpy array to PyTorch tensor.

**To Reproduce**
1. Use the embedding layer
2. Pass some data using the fit method

The embedding layer requires the input to be in Long type, however, all other layers requires the input to be in Float type.
Currently, in the model, hardcoded to convert everything into Float. That is causing an issue.

**Expected behavior**
In an ideal situation, there should be a function that converts the numpy array into PyTorch tensor and **keep the data type same**.

**Additional context**
Here is the line of code that is causing the issue:
  - https://github.com/imdeepmind/NeuralPy/blob/master/neuralpy/models/model.py#L111
  - https://github.com/imdeepmind/NeuralPy/blob/master/neuralpy/models/model.py#L99
  - https://github.com/imdeepmind/NeuralPy/blob/master/neuralpy/models/model.py#L188
  - and in some other places

This is how we're converting a numpy array to tensor:
  - https://github.com/imdeepmind/NeuralPy/blob/855c9305e4c11ff297c5c61a71739dff9b6b7089/neuralpy/models/model.py#L175

**Comment by jeffin07** [comment]
So the solution is a function that handles the type conversion?And why is everything is converting to float ?

**Comment by imdeepmind** [comment]
That is the issue, I think let's so one thing. Let's use the `from_numpy` function. And don't convert the data type of the input. The user needs to convert the numpy array to specific data types, so we don't need to handle the data type conversion.

**Comment by jeffin07** [comment]
@imdeepmind Is there any change required? Why is this closed?
