### ISSUE TITLE
Discussion thread on the next major release of NeuralPy after v0.2.0-alpha

### ISSUE THREAD

**Issue by imdeepmind** [imdeepmind/NeuralPy#75]
Here we can discuss on what features to add on the next major release of Nueralpy `v0.3.0-alpha`

**Comment by imdeepmind** [comment]
This library prints the summary of the model in an interesting way, need to have a look at the code. We can implement something like this in NeuralPy.

**Comment by jeffin07** [comment]
More Examples and maybe the available datasets to train and test neuralpy models

**Comment by jeffin07** [comment]
Need a Dataset class which contains the popular datasets which can be used to train and test model and also their post-processing class for transforming the datasets 

[datasets](https://keras.io/api/datasets/)
[post-processing](https://keras.io/api/preprocessing/)
