### ISSUE TITLE
First Release Plan

### ISSUE THREAD

**Issue by imdeepmind** [imdeepmind/NeuralPy#8]
Hello World!!!

My target is to release NeuralPy version `0.1-alpha` by Wednesday 10th June. 

Most of the work is finished, except for a few. Here is a detailed list of pending tasks:

- Test Cases for Sequential Model
- Code Refactoring and big fixes for Sequential Model
- Completing the Documentation on Sequential Model
- Added an Advanced Topic section on the documentation (shows how to use a custom layer/loss function/ optimizer etc)
- Documentation review for any typoes/grammatical mistakes/improvements/broken links etc
- Added some example project, so people can get started
- Any other bugs or other improvements that I notice

**Comment by imdeepmind** [comment]
Will be delayed by some days

**Comment by jeffin07** [comment]
@imdeepmind  I would like to work on neuralpy. Would you help me to get started or is there any issues that you want me to work on ?

**Comment by imdeepmind** [comment]
@jeffin07 Thanks for showing interest in this project. As this project is at a very early stage of development, there are thousands of stuff that you can do. 

You can add support to new types of **Layers, Activation Functions, Loss Functions, Optimizers,** etc.

Also, I'm thinking about adding support to Layer, Loss Function, and Optimizer base class that can be used to generate other NeuralPy supported Layers/Loss Functions/Optimizers. I have already achieved it for the Model module. If you check the code, then there is a Model class that provides different methods like `fit`, `predict`, etc.  The Sequential Model class inherits the Model class and use the methods provided by the Model class to build the Sequential model.

Finally, there are several bugs in the code, so if you notice one, you can submit a PR. You can work on the code improvement also.

If you need more info, please contact me.

I'm also sharing this Discord invitation link, you can join if you want to discuss anything with me.
Discord Link: https://discord.gg/6aTTwbW

Note: **I'll release the first alpha version in 2-3 days. So I'll not accept any new features now. If you submit PR for new features, I'll merge it after some days, once I release the first version.**

**Comment by imdeepmind** [comment]
As I have already released the first version, I'm closing this issue
