### ISSUE TITLE
Issues with BatchNorm layers

### ISSUE THREAD

**Issue by imdeepmind** [imdeepmind/NeuralPy#87]
**Describe the bug**
There are several issues with batchnorm layers that needed to be resolved before the release. Here is a list of all the issues with the layer.

- BatchNorm1D layer can not be used before Dense layer
- The "D" in batchnorm layers are in small case, we're following a convention to denote the "D" in capital letters
- The `num_feature` is not optional, it should be optional
- The 'get_input_dim' method has some issues
- Some other issues

**Comment by imdeepmind** [comment]
Started working on some of the issues

**Comment by jeffin07** [comment]
@imdeepmind What are the issues that you're not working right now ?
